services:
  bot:
    volumes:
      - ./src:/app/src
  celery_worker:
    volumes:
      - ./src:/app/src
  celery_beat:
    volumes:
      - ./src:/app/src
  migrations:
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
  loki:
    ports:
      - "127.0.0.1:3100:3100"
  grafana:
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards
