apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: pg-mentoring
    type: postgres
    access: proxy
    url: db:5432
    database: ${DB_NAME}
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASS}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    isDefault: true
    editable: false
