"""add name for rules

Revision ID: 435ea526d448
Revises: ae7bd9120402
Create Date: 2025-12-15 12:25:41.832920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '435ea526d448'
down_revision: Union[str, Sequence[str], None] = 'ae7bd9120402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state_rules', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('user_rules', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_rules', 'name')
    op.drop_column('state_rules', 'name')
    # ### end Alembic commands ###
